### ISSUE TITLE
[Suggestion] Option to disable the advancement & chat text on first world load.

### ISSUE THREAD

**Issue by Gbergz** [coolsimulations/SurvivalPlus#1]
Title^

An option to disable the advancement & chat messages when loading up a fresh new world.
Example:
![asd](https://user-images.githubusercontent.com/26634554/74604541-4aac4180-50bf-11ea-8a55-8a448f454164.PNG)
![dsa](https://user-images.githubusercontent.com/26634554/74604542-4da73200-50bf-11ea-9d72-50d1447f0111.PNG)

Using 1.15.2 version of the mod.

- Gbergz

**Comment by coolsimulations** [comment]
Alright, I am adding that config option into Version 0.1.3, this will also affect MoreThanAPickaxe and SurvivalPlus Lightsabers. However, there's nothing I can do about the advancement, it stays how it is.

**Comment by Gbergz** [comment]
No problem! Just the message i was upset about. Glad a config option will be added for it. :)
