### ISSUE TITLE
[1.18.2] Compat issue with ProjectE

### ISSUE THREAD

**Issue by Baggytrousers27** [coolsimulations/SurvivalPlus#11]
SurvivalPlus-1.18.2-0.1.6c
ProjectE-1.18.2-PE1.0.0
Forge 40.0.32

[Crashlog](https://pastebin.com/Nm8gkunM)

Something about Raw Tin?

**Comment by coolsimulations** [comment]
Fixed with https://github.com/coolsimulations/SurvivalPlus/commit/79ee1d854bbe4082c08948bbf9cdcaaeb1e249e9. Version 0.1.6d is on CurseForge.

**Comment by Baggytrousers27** [comment]
Cheers and thanking you muchly.
