### ISSUE TITLE
Pre-launch crash

### ISSUE THREAD

**Issue by Wajiro** [coolsimulations/SurvivalPlus#14]
[Fabric Loader 0.14.10 / Minecraft 1.19.2]
Here are the crash report and the latest log file. I don't know it's the fault of SurvivalPlus itself or it's due to a mixin incompatibility.

[crash-2022-10-27_19.33.49-client.txt](https://github.com/coolsimulations/SurvivalPlus/files/9881254/crash-2022-10-27_19.33.49-client.txt)

[latest.log](https://github.com/coolsimulations/SurvivalPlus/files/9881255/latest.log)

**Comment by coolsimulations** [comment]
If you remove `SurvivalPlus` and `MoreThanAPickaxe`, then create a new world. Can you find out for me what mods add in a tin ore block?

**Comment by Wajiro** [comment]
[Revolutionary Bronze](https://www.curseforge.com/minecraft/mc-mods/revolutionary-bronze)
[Mythic Metals](https://www.curseforge.com/minecraft/mc-mods/mythicmetals)
[Dadobug1111's Bedrock Ores](https://www.curseforge.com/minecraft/mc-mods/dadobug1111s-bedrock-ores) (which has compatibility with Mythic Metals and inherited its tin ore)

**Comment by Wajiro** [comment]
Any update?

**Comment by coolsimulations** [comment]
Fixed in 0.1.7 with https://github.com/coolsimulations/SurvivalPlus/commit/cbe4f8351b8bb5c82f2f3806ed320d3b73738be0
