### ISSUE TITLE
"coolsim" added to whitelist at startup

### ISSUE THREAD

**Issue by calliecameron** [coolsimulations/SurvivalPlus#19]
When the mod starts up, it adds coolsim to the server whitelist. The whitelist should be under the control of the server admin, especially on a private server - just because I use your mod, doesn't mean I want you to be able to join my server.

Please stop the mod doing this, or at least add a way to disable it. From the code, it looks like I can stop it by banning coolsim, but if this 'feature' is kept, it should be prominently documented since it breaks admin expectations.

Using the latest version for 1.19.2 fabric.

**Comment by coolsimulations** [comment]
SurvivalPlus is currently going through a massive rewrite to support Fabric, Forge, NeoForge, and Quilt in the same multi-loader workspace, which just means development can happen on all four at the same time. As part of this rewrite, this unadvertised feature will be removed to avoid any security concerns.
