### ISSUE TITLE
SurvivalPlus not working with Base Metals latest version

### ISSUE THREAD

**Issue by Keetarin** [coolsimulations/SurvivalPlus#2]
Mods used in Test Pack
Minecraft - 1.12.2
Forge - forge-14.23.5.2847
Base Metals - _Versions shown in links_
MMD OreSpawn - OreSpawn-1.12-3.3.1.179.jar
MMDLib - MMDLib-1.12-1.0.0-rc2.36.jar
SurvivalPlus - SurvivalPlus-1.12.2-0.1.2.jar
Heres the test logs starting from the latest version of Base Metals working my way backwards to a potentially compatible version:
[Base Metals 2.5.0-rc2.332 - Incompatible](https://pastebin.com/pq3KVqyT)
[Base Metals 2.5.0-rc1.332 - Incompatible](https://pastebin.com/0a8kXKsH)
[Base Metals 2.5.0-beta7.311 - Incompatible](https://pastebin.com/xXYbixtL)
[Base Metals 2.5.0-beta6.280 - Incompatible](https://pastebin.com/uTBRaD0F)
[BaseMetals-1.12-2.5.0-beta5.214.jar - Incompatible](https://pastebin.com/VDJ2jeE2)
Note: My cat is being a pill, so I'll finish later.
Edit 1/1: 
[Base Metals 2.5.0-beta4.145 - Incompatible](https://pastebin.com/in3T4MgJ)
[Base Metals 2.5.0-beta3.51 - Incompatible](https://pastebin.com/SfcpsMM5)
[Base Metals 2.5.0-beta2.44 - Incompatible](https://pastebin.com/NZXvTeEa)
[Base Metals 2.5.0-beta2.31 - Incompatible](https://pastebin.com/bsDpGZtx)
[Base Metals 2.5.0-beta2.29 - Incompatible](https://pastebin.com/5Fb5WTjM)
[Base Metals 2.5.0-beta2.26 - Incompatible](https://pastebin.com/LXgSshKY)
[Base Metals 2.5.0-beta2.23 - Incompatible](https://pastebin.com/MEtYtR46)
I've tested all available versions of Base Metals on curseforge for 1.12.2,
SurvivalPlus has rejected all of them,

**Comment by coolsimulations** [comment]
Thanks for the thorough testing! The crash is just simply because I have the wrong minimum version number. [Andy_Cool06 mentioned this issue before](https://www.curseforge.com/minecraft/mc-mods/survivalplus?comment=25) but the good news is that it has already been fixed in the new SurvivalPlus version 0.1.3 that I'm working on. Not sure when it'll come out yet, but rest assured this has been resolved.
