### ISSUE TITLE
Bronze/Copper Blocks not crafting to ingots

### ISSUE THREAD

**Issue by ClaudiusMinimus** [coolsimulations/SurvivalPlus#3]
Both copper and bronze cannot be crafting into ingots - if you put a block in a crafting table there is no output.

SurvivalPlus-1.16.1-0.1.3

**Comment by coolsimulations** [comment]
Thanks for finding this. It's actually a bug in 1.14-1.16 due to my new compatibility for Silent's Mechanisms. This bug also affects the bronze/copper nuggets as well as the block to nugget recipes too. This has been fixed and will be released with the 0.1.4 update sometime in the future.

**Comment by coolsimulations** [comment]
Don't ask me how cause I have *no clue*, but I did fix this, tested the fix and uploaded the fix for this issue. But when playing with 0.1.4b it's still broken and I can't find any trace of my fix so I'll release a new b version for 1.14/1.15 and a c version for 1.16 that'll fix this again.
