### ISSUE TITLE
Crash with nether ex on server

### ISSUE THREAD

**Issue by raffycaccia** [coolsimulations/SurvivalPlus#4]
--- Minecraft Crash Report ---
`
---- Minecraft Crash Report ----
// Don't do that.

Time: 01/08/20 15.23
Description: Exception in server tick loop

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	SurvivalPlus (survivalplus) has failed to load correctly
§7null
]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:218) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:200) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows Server 2019 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3360118776 bytes (3204 MB) / 4401922048 bytes (4198 MB) up to 7680294912 bytes (7324 MB)
	CPUs: 4
	JVM Flags: 2 total; -Xms2048M -Xmx8240M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge.jar object_holder_definalize PLUGINSERVICE 
		/forge.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge.jar capability_inject_definalize PLUGINSERVICE 
		/forge.jar runtimedistcleaner PLUGINSERVICE 
		/forge.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.31
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 CREATE_REGISTRIES}
		better-food-1.15.2-0.2.0.jar Better Food {better-food@1.15.2-0.2.0 CREATE_REGISTRIES}
		Wyrmroost-1.1.2.jar Wyrmroost {wyrmroost@1.1.1-DEV CREATE_REGISTRIES}
		Bountiful Baubles-1.15.2-0.0.1.jar Bountiful Baubles {bountifulbaubles@NONE CREATE_REGISTRIES}
		jei-1.15.2-6.0.2.12.jar Just Enough Items {jei@6.0.2.12 CREATE_REGISTRIES}
		enchantable-1.3.0-1.15.2.jar Enchantable {enchantable@1.3.0 CREATE_REGISTRIES}
		prefab-1.5.0.9.jar Prefab {prefab@1.5.0.9 CREATE_REGISTRIES}
		0.0.5c-releasecandidate1.jar NetherBackport {netherbackport@1.0.0 CREATE_REGISTRIES}
		Abnormals-Core-1.15.2-1.0.6.jar Abnormals Core {abnormals_core@1.0.6 CREATE_REGISTRIES}
		goblintraders-1.2.0-1.15.2.jar Goblin Traders {goblintraders@1.2.0 CREATE_REGISTRIES}
		strawgolem-1.15.2-1.7.1.jar Straw Golem {strawgolem@1.15.2-1.7.1 CREATE_REGISTRIES}
		BetterCaves-1.15.2-1.0.jar YUNG's Better Caves {bettercaves@1.15.2-1.0 CREATE_REGISTRIES}
		Waystones_1.15.2-6.0.2.jar Waystones {waystones@6.0.2 CREATE_REGISTRIES}
		ForgeEndertech-1.15.2-6.0.4.0-build.0044.jar Forge Endertech {forgeendertech@6.0.4.0 CREATE_REGISTRIES}
		Clumps-5.0.2.4.jar Clumps {clumps@5.0.2.4 CREATE_REGISTRIES}
		journeymap-1.15.2-5.7.0b3.jar Journeymap {journeymap@5.7.0b3 CREATE_REGISTRIES}
		Controlling-6.1.5.6.jar Controlling {controlling@6.1.5.6 CREATE_REGISTRIES}
		Placebo-1.15.2-3.1.0.jar Placebo {placebo@3.1.0 CREATE_REGISTRIES}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 CREATE_REGISTRIES}
		EnderBags-1.15.2-5.0.2.jar Ender Bags {ender_bags@5.0.2 CREATE_REGISTRIES}
		SereneSeasons-1.15.2-3.0.0.73-universal.jar Serene Seasons {sereneseasons@1.15.2-3.0.0.73 CREATE_REGISTRIES}
		champions-FORGE-1.15.2-2.0-beta5.jar Champions {champions@FORGE-1.15.2-2.0-beta5 CREATE_REGISTRIES}
		MutantBeasts-1.15.2-1.0.7.jar Mutant Beasts {mutantbeasts@1.15.2-1.0.7 CREATE_REGISTRIES}
		Bookshelf-1.15.2-5.6.40.jar Bookshelf {bookshelf@5.6.40 CREATE_REGISTRIES}
		Cursed-1.15.2-2.0.6.jar Cursed {cursed@2.0.6 CREATE_REGISTRIES}
		guardvillagers-1.15.2-1.0.8.jar Guard Villagers {guardvillagers@1.0.7 CREATE_REGISTRIES}
		u_team_core-1.15.2-3.0.1.164.jar U Team Core {uteamcore@3.0.1.164 CREATE_REGISTRIES}
		Apotheosis-1.15.2-3.2.4.jar Apotheosis {apotheosis@3.2.4 CREATE_REGISTRIES}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version CREATE_REGISTRIES}
		WAWLA-1.15.2-3.0.4.jar WAWLA {wawla@3.0.4 CREATE_REGISTRIES}
		WaterStrainer-1.15.2-9.0.0.jar Water Strainer {waterstrainer@1.15.2-9.0.0 CREATE_REGISTRIES}
		forge-1.15.2-31.2.31-universal.jar Forge {forge@31.2.31 CREATE_REGISTRIES}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 CREATE_REGISTRIES}
		forge-1.15.2-31.2.31-server.jar Minecraft {minecraft@1.15.2 CREATE_REGISTRIES}
		cofh_core-1.15.2-0.4.0b.jar CoFH Core {cofh_core@0.4.0b CREATE_REGISTRIES}
		ensorcellation-1.15.2-0.4.1b.jar Ensorcellation {ensorcellation@0.4.1b CREATE_REGISTRIES}
		The-Endergetic-Expansion-1.15.2-v1.3.2.jar The Endergetic Expansion {endergetic@1.3.2 CREATE_REGISTRIES}
		lightestlamp-3.4.3.jar Lightest Lamps {lightestlamp@3.4.3 CREATE_REGISTRIES}
		FarmersDelight-1.15.2-0.1.2.jar Farmer's Delight {farmersdelight@1.15.2-0.1.2 CREATE_REGISTRIES}
		useful_backpacks-1.15.2-1.10.1.70.jar Useful Backpacks {usefulbackpacks@1.10.1.70 CREATE_REGISTRIES}
		torchmaster-2.2.2.jar Torchmaster {torchmaster@2.2.2 CREATE_REGISTRIES}
		EnchantmentDescriptions-1.15.2-2.0.9.jar EnchantmentDescriptions {enchdesc@2.0.9 CREATE_REGISTRIES}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 CREATE_REGISTRIES}
		pandoras_creatures-1.15.2-1.0.0.jar Pandoras Creatures {pandoras_creatures@1.15.2-1.0.0 CREATE_REGISTRIES}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 CREATE_REGISTRIES}
		netherportalspread_1.15-3.5.jar Nether Portal Spread {netherportalspread@3.5 CREATE_REGISTRIES}
		BetterCrates-1.15.2-1.0.0.jar Better Crates {bettercrates@1.0.0 CREATE_REGISTRIES}
		morevanillalib-1.15.2-1.2.2.jar MoreVanillaLib {morevanillalib@1.2.2 CREATE_REGISTRIES}
		valhelsia_structures-15.0.3a.jar Valhelsia Structures {valhelsia_structures@15.0.3a CREATE_REGISTRIES}
		HardcoreBattleTowers_3.0.0.jar  Harcore Battle Towers UPDATE {harcorebattletowers@Official Remake v3.0.0 CREATE_REGISTRIES}
		LagsLib-1.15.2-1.0.0.jar Lag's Lib {lagslib@1.0.0 CREATE_REGISTRIES}
		forbidden_arcanus-1.15.2-1.4.jar Forbidden & Arcanus {forbidden_arcanus@1.15.2-1.4 CREATE_REGISTRIES}
		AdLods-1.15.2-3.0.3.0-build.0035.jar Large Ore Deposits {adlods@3.0.3.0 CREATE_REGISTRIES}
		archers_paradox-1.15.2-0.4.0b.jar Archer's Paradox {archers_paradox@0.4.0b CREATE_REGISTRIES}
		towers_of_the_wild-1.15.2-1.2.0.jar Towers Of the Wild {towers_of_the_wild@1.15.2-1.2.0 CREATE_REGISTRIES}
		foodpouches_1.15.2-1.0.jar Food Pouches {foodpouches@1.15.2-1.0 CREATE_REGISTRIES}
		curios-FORGE-1.15.2-2.0.2.4.jar Curios API {curios@FORGE-1.15.2-2.0.2.4 CREATE_REGISTRIES}
		Artifacts-1.15.2-2.3.0.jar Artifacts {artifacts@1.15.2-2.3.0 CREATE_REGISTRIES}
		Savage-and-Ravage-1.15.2-1.1.4.jar Savage & Ravage {savageandravage@1.1.4 CREATE_REGISTRIES}
		collective-1.15.2-1.35.jar Collective {collective@1.35 CREATE_REGISTRIES}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 CREATE_REGISTRIES}
		Quark-r2.1-245.jar Quark {quark@r2.1-245 CREATE_REGISTRIES}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 CREATE_REGISTRIES}
		OreExcavation-1.7.151.jar Ore Excavation {oreexcavation@NONE CREATE_REGISTRIES}
		EndReborn [0.6.0].jar End: Reborn {endreborn@0.6.0 CREATE_REGISTRIES}
		vanillahammers-1.15.2-2.1.jar Vanilla Hammers {vanillahammers@2.1 CREATE_REGISTRIES}
		Regrowth-1.15.2-1.0.0.1.jar Regrowth Mod {regrowth@1.0.0.1 CREATE_REGISTRIES}
		Gobber2-1.15.2-2.2.102.jar Gobber 2 {gobber2@2.2.99 CREATE_REGISTRIES}
		ProjectExtended-1.15.2-1.1.0.jar ProjectExtended {projectextended@1.1.0 CREATE_REGISTRIES}
		AppleSkin-mc1.15.2-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 CREATE_REGISTRIES}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 CREATE_REGISTRIES}
		byg-1.0.10.jar Oh The Biomes You'll Go {byg@1.0.10 CREATE_REGISTRIES}
		Charm-1.15.2-1.5.9.jar Charm {charm@1.15.2-1.5.9 CREATE_REGISTRIES}
		Strange-1.15.2-1.0.0-beta.5.hotfix1.jar Strange {strange@1.15.2-1.0.0-beta.5 CREATE_REGISTRIES}
		MoreThanAPickaxe-1.15.2-0.1.3.jar More Than A Pickaxe {morethanapickaxe@0.1.3 CREATE_REGISTRIES}
		SurvivalPlus-1.15.2-0.1.3.jar SurvivalPlus {survivalplus@0.1.3 ERROR}
		ProjectE-1.15.2-PE1.0.4.jar ProjectE {projecte@1.0.4 CREATE_REGISTRIES}
		JustEnoughResources-1.15.2-0.10.1.77.jar Just Enough Resources {jeresources@0.10.1.77 CREATE_REGISTRIES}
		FastLeafDecay-v22.jar FastLeafDecay {fastleafdecay@v22 CREATE_REGISTRIES}
		CodeChickenLib-1.15.2-3.3.1.379-universal.jar CodeChicken Lib {codechickenlib@3.3.1.379 CREATE_REGISTRIES}
		EnderStorage-1.15.2-2.5.0.149-universal.jar EnderStorage {enderstorage@2.5.0.149 CREATE_REGISTRIES}
		NetherEx-1.15.2-4.0.0.jar NetherEx {netherex@4.0.0 CREATE_REGISTRIES}
		LibraryEx-1.15.2-3.0.0.jar LibraryEx {libraryex@3.0.0 CREATE_REGISTRIES}
		WailaHarvestability-mc1.15.2-1.1.12.jar Waila Harvestability {wailaharvestability@1.1.12 CREATE_REGISTRIES}
		Cyclic-1.15.2-0.6.1.jar Cyclic {cyclic@1.15.2-0.6.1 CREATE_REGISTRIES}
	Data Packs: 
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

`

removing the nether ex everything works

**Comment by coolsimulations** [comment]
This is a very strange issue. I tried putting SurvivalPlus and NetherEx alone together and they worked so that's not the issue. I then downloaded all the mods in your pack and the server ran fine without issue. Because SurvivalPlus supports so many mods it's generally one of the last mods to load, which can mean that it takes the blame for a crash when it didn't cause it. But since I can't recreate this crash I can't do anything about this.
