### ISSUE TITLE
Error on Startup (Won't Load)

### ISSUE THREAD

**Issue by Camawama** [coolsimulations/SurvivalPlus#5]
I am running the latest version of your mod for Forge 32.0.98 and I get this error when starting up the game

Console: 
![image](https://user-images.githubusercontent.com/43620900/89573407-2e789a00-d7f0-11ea-896f-eda8aa8caded.png)

Game Window: 
![image](https://user-images.githubusercontent.com/43620900/89573453-3cc6b600-d7f0-11ea-8a2e-1b763d43517c.png)

**Comment by coolsimulations** [comment]
Thanks for reporting this! I have fixed this issue with the new 1.16.1-0.1.3b version that I am uploading now.
