### ISSUE TITLE
Everything is fuel...

### ISSUE THREAD

**Issue by dreaderinyes** [coolsimulations/SurvivalPlus#7]
For whatever your mod is making it so nearly every block burns in a furnace and smelts 6 items. I tested it in a modpack with just survivalplus and jei to make sure.

**Comment by coolsimulations** [comment]
Before I can comment on this, is this Forge or Fabric? And what Minecraft version is this issue occurring on?

**Comment by dreaderinyes** [comment]
Forge 36.2, 1.16.5, every version of the mod available through curse did it.

**Comment by Baggytrousers27** [comment]
Forge 1.17.1 37.0.30 all the way to 37.0.44.
Just smelted 6 mutton in a furnace using another furnace as the fuel.

**Comment by coolsimulations** [comment]
Fixed with https://github.com/coolsimulations/SurvivalPlus/commit/4b6f993e1fc292df17694decb1b94a0bca08d6fe. Will be released as part of 0.1.5b for 1.14-1.16 and 0.1.6 for 1.17-1.18.

**Comment by Baggytrousers27** [comment]
![heck yeah dance](https://user-images.githubusercontent.com/15883796/144795248-2581341d-1097-459f-97ff-b5b3468be4d9.gif)
